version: '3'
tasks:
  db:
    cmds:
      - |
        docker run --name dev-postgres \
        -e POSTGRES_USER=devuser \
        -e POSTGRES_PASSWORD=devpass \
        -e POSTGRES_DB=devdb \
        -p 5432:5432 \
        -v pgdata:/var/lib/postgresql/data \
        -d postgres:16
