version: '3'
tasks:
  db:
    cmds:
      - |
        docker run --rm --name dev-postgres \
        -e POSTGRES_USER=devuser \
        -e POSTGRES_PASSWORD=devpass \
        -e POSTGRES_DB=devdb \
        -p 5432:5432 \
        -d postgres:16
  db-down:
    cmds:
      - "docker stop dev-postgres"
