// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type File struct {
	ID            int32          `json:"id"`
	OwnerGoogleID sql.NullString `json:"owner_google_id"`
	FileName      string         `json:"file_name"`
	FileType      sql.NullString `json:"file_type"`
	Size          sql.NullInt64  `json:"size"`
	Md5Checksum   string         `json:"md5_checksum"`
}

type Share struct {
	ID           int32          `json:"id"`
	SharedBy     sql.NullString `json:"shared_by"`
	SharedFor    sql.NullString `json:"shared_for"`
	SharingToken string         `json:"sharing_token"`
	FileID       sql.NullInt32  `json:"file_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

type User struct {
	GoogleID   string         `json:"google_id"`
	UserName   sql.NullString `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserBucket sql.NullString `json:"user_bucket"`
}
