// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: shares.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getFilesSharedWithUser = `-- name: GetFilesSharedWithUser :many
SELECT f.id, f.owner_google_id, f.file_name, f.file_type, f.size, f.md5_checksum
FROM shares s
JOIN files f ON s.file_id = f.id
WHERE s.shared_for = $1
`

func (q *Queries) GetFilesSharedWithUser(ctx context.Context, sharedFor sql.NullString) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesSharedWithUser, sharedFor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerGoogleID,
			&i.FileName,
			&i.FileType,
			&i.Size,
			&i.Md5Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShare = `-- name: InsertShare :one
INSERT INTO shares (shared_by, shared_for, file_id, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (shared_by, shared_for, file_id) DO UPDATE
SET expires_at = EXCLUDED.expires_at
RETURNING id, shared_by, shared_for, file_id, created_at, expires_at
`

type InsertShareParams struct {
	SharedBy  sql.NullString `json:"shared_by"`
	SharedFor sql.NullString `json:"shared_for"`
	FileID    sql.NullInt32  `json:"file_id"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) InsertShare(ctx context.Context, arg InsertShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, insertShare,
		arg.SharedBy,
		arg.SharedFor,
		arg.FileID,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SharedBy,
		&i.SharedFor,
		&i.FileID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
